name = "courses"
type = 'javascript'

account_id = "3a437d2b23c924eb40f67418fd3da664"
workers_dev = true

main = "src/index.js"
compatibility_date = "2023-01-25"

[vars]
AIRTABLE_BASE_ID = "app3ha8WdLV7nJGBq"
AIRTABLE_TABLE_NAME = "Courses"
AIRTABLE_URL='https://api.airtable.com/v0'
FORM_URL = "https://course-tracker-bdn.pages.dev/"
